name: MacOS build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  macos-build:
    # Name the Job
    name: Build for MacOS
    # Set the type of machine to run on
    # Qt doesn't currently like 11.0, so we don't use macos-latest
    runs-on: macos-10.15

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Based on https://gist.github.com/ruario/b83c1030790948d66c624aa99203140c
      # to unpack the DMG
      - name: Install VLC
        timeout-minutes: 2
        run: |
            curl 'https://ftp.osuosl.org/pub/videolan/vlc/3.0.12/macosx/vlc-3.0.12-intel64.dmg' -o /tmp/vlc.dmg
            df -h
            mkdir /tmp/vlc
            hdiutil attach "/tmp/vlc.dmg" -mountpoint "/tmp/vlc" -nobrowse
            echo "Finished attaching dmg"
            cp -r /tmp/vlc/VLC.app /Applications/VLC.app

      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: Build SdPlayer
        run: |
            qmake -config release
            make
            echo Adding RPATH
            install_name_tool -add_rpath /Applications/VLC.app/Contents/MacOS/lib SdPlayer.app/Contents/MacOS/SdPlayer
            echo Checking RPATH
            otool -l SdPlayer.app/Contents/MacOS/SdPlayer | grep -B2 -A5 RPATH

      - name: Add extra assets
        run: |
            cp filetypes.txt *.png SdPlayer.app/Contents/MacOS
            mkdir SdPlayer.app/Contents/krubow
            cp assets/sdplayer.ini SdPlayer.app/Contents/krubow/

      - name: Fetch icons
        run: |
            curl -o Music.icns "https://wikis.mit.edu/confluence/download/attachments/139234615/Music.icns?api=v2"
            cp Music.icns SdPlayer.app/Contents/Resources

      - name: Create DMG
        run: macdeployqt SdPlayer.app -dmg

      - name: Save DMG
        uses: actions/upload-artifact@v2
        with:
            name: SdPlayer
            path: SdPlayer.dmg
