name: Windows build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  win-build:
    # Name the Job
    name: Build for Windows
    # Set the type of machine to run on
    # Qt doesn't currently like 11.0, so we don't use macos-latest
    runs-on: windows-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3

      # Download and install VLC
      - name: Install VLC
        timeout-minutes: 2
        run: |
            cd ..
            curl https://ftp.osuosl.org/pub/videolan/vlc/3.0.18/win64/vlc-3.0.18-win64.7z -o vlc.7z
            7z x vlc.7z

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
            arch: win64_mingw81

      - name: Build SdPlayer - qmake
        run: |
            qmake -config release -platform win32-g++
            mingw32-make
            ls -R

      - name: Save exe
        uses: actions/upload-artifact@v3
        with:
            name: SdPlayer.exe
            path: release/SdPlayer.exe

      - name: Add extra assets
        run: |
            cp filetypes.txt *.png SdPlayer.app/Contents/MacOS
            mkdir SdPlayer.app/Contents/krubow
            cp assets/sdplayer.ini SdPlayer.app/Contents/krubow/

      - name: Fetch icons
        run: |
            curl -o Music.icns "https://wikis.mit.edu/confluence/download/attachments/139234615/Music.icns?api=v2"
            cp Music.icns SdPlayer.app/Contents/Resources

      - name: Create DMG
        run: macdeployqt SdPlayer.app -dmg

      - name: Save DMG
        uses: actions/upload-artifact@v3
        with:
            name: SdPlayer
            path: SdPlayer.dmg
