name: Windows build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  win-build:
    # Name the Job
    name: Build for Windows
    # Set the type of machine to run on
    # Qt doesn't currently like 11.0, so we don't use macos-latest
    runs-on: windows-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3

      # Fixes missing compiler error on build -- from
      # https://forum.qt.io/topic/137995/github-workflow-cannot-run-compiler-cl/4
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

        # GitHub suggests using choco to install packages
        # https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-windows-runners
      - name: Install VLC
        timeout-minutes: 2
        run: choco install vlc

      - name: Install Qt
        uses: jurplel/install-qt-action@v3

      - name: Build SdPlayer - qmake
        run: |
            qmake -config release

      - name: Save qmake outputs
        uses: actions/upload-artifact@v3
        with:
            name: SdPlayer qmake
            path: Makefile*

      - name: Build SdPlayer - more steps
        run: |
            make
            cat Makefile.release
            cat Makefile.debug
            ls -R release
            ls -R

      - name: Add extra assets
        run: |
            cp filetypes.txt *.png SdPlayer.app/Contents/MacOS
            mkdir SdPlayer.app/Contents/krubow
            cp assets/sdplayer.ini SdPlayer.app/Contents/krubow/

      - name: Fetch icons
        run: |
            curl -o Music.icns "https://wikis.mit.edu/confluence/download/attachments/139234615/Music.icns?api=v2"
            cp Music.icns SdPlayer.app/Contents/Resources

      - name: Create DMG
        run: macdeployqt SdPlayer.app -dmg

      - name: Save DMG
        uses: actions/upload-artifact@v3
        with:
            name: SdPlayer
            path: SdPlayer.dmg
