name: Windows build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  win-build:
    # Name the Job
    name: Build for Windows
    # Set the type of machine to run on
    # Qt doesn't currently like 11.0, so we don't use macos-latest
    runs-on: windows-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3

      # Download and install VLC
      - name: Install VLC
        timeout-minutes: 2
        run: |
            cd ..
            curl https://ftp.osuosl.org/pub/videolan/vlc/3.0.18/win64/vlc-3.0.18-win64.7z -o vlc.7z
            7z x vlc.7z

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
            arch: win64_mingw81

      - name: Build SdPlayer
        run: |
            qmake -config release -config windeployqt -platform win32-g++
            mingw32-make
            windeployqt --dir installdir release/SdPlayer.exe

      - name: Save exe
        uses: actions/upload-artifact@v3
        with:
            name: SdPlayer.exe
            path: release/SdPlayer.exe

      - name: Prep installdir
        run: |
            cp release/SdPlayer.exe installdir/
            Copy-Item filetypes.txt,assets/sdplayer.ini,*.png installdir/
            Copy-Item -Recurse ../vlc-3.0.18/libvlc.dll,../vlc-3.0.18/libvlccore.dll,../vlc-3.0.18/plugins/ installdir/
            Copy-Item "C:/Program Files/Git/mingw64/bin/libwinpthread-1.dll","C:/Program Files/Git/mingw64/bin/libstdc++-6.dll","C:/Program Files/Git/mingw64/bin/libgcc_s_seh-1.dll" installdir/

      - name: Build installer
        run: |
            # Path from https://github.com/orgs/community/discussions/27149
            $env:Path += ";C:/Program Files (x86)/WiX Toolset v3.11/bin"
            # -cg: ComponentGroup to reference
            # -dr: Directory to put things under
            # -srd: Place files directly under INSTALLDIR, not a subdir
            # -var: Instead of using SourceDir as the source path, use a var that we can set to installdir
            # -gg: Generate GUIDs now
            # -sfrag: ??? In https://stackoverflow.com/questions/36756311/include-all-files-in-bin-folder-in-wix-installer
            # -swHEAT5150: Ignore warnings because 64-bit DLLs can't be checked for self-reg
            # -template: Make a fragment to include
            # -out: File to put output in
            heat dir installdir/ -cg InstallDirComps -dr INSTALLDIR -srd -var var.SrcInstallDir -gg -sfrag -sw5150 -template fragment -out installdir.wxs
            candle -arch x64 -ext WixUIExtension -ext WixUtilExtension sdplayer.wxs
            candle -arch x64 -dSrcInstallDir=installdir installdir.wxs
            light -ext WixUIExtension -ext WixUtilExtension -o SdPlayer.msi sdplayer.wixobj installdir.wixobj

      - name: Save installer
        uses: actions/upload-artifact@v3
        with:
            name: SdPlayer Windows installer
            path: |
                SdPlayer.msi
